walmart_upc/__init__.py
"""
"A universal convention supplies all of maintainability,
clarity, consistency, and a foundation for good programming habits too.
What it doesn't do is insist that you follow it against your will. That's Python!"
—Tim Peters on comp.lang.python, 2001-06-16
"""
from flask import Flask
from flask_adminlte import AdminLTE
from flask_login import LoginManager
from walmart_upc.controllers import authorization, main
import walmart_upc.model as Model


def create_flask_odj():
    """ Configures flask object """

    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object('settings')
    app.config.from_pyfile('log_settings.py')
    lm = LoginManager()
    lm.init_app(app)
    lm.session_protection = 'strong'
    lm.login_view = "auth.login"
    Model.db.init_app(app)
    AdminLTE(app)
    @lm.user_loader
    def load_user(email):

        try:
            return Model.UserModel.objects.get(email=email)
        except:
            return None
    return app


def create_app():
    """ Return flask object """

    app = create_flask_odj()
    app.register_blueprint(authorization.auth)
    app.register_blueprint(main.main)
    return app

if __name__ == '__main__':
    create_app().run(debug=True)

walmart_upc/controllers/authorization.py
"""
"A universal convention supplies all of maintainability,
clarity, consistency, and a foundation for good programming habits too.
What it doesn't do is insist that you follow it against your will. That's Python!"
—Tim Peters on comp.lang.python, 2001-06-16
"""
from flask import render_template, request, \
 redirect, Blueprint, flash
from flask_login import login_user, logout_user
import walmart_upc.objects_behevior as model
from walmart_upc.form import LoginForm, RegistrationForm

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['POST', 'GET'])
def login():
    """ Return login.html if you don't authorized """

    form = LoginForm()
    if form.validate_on_submit():
        user = model.User.get_user(form.username.data, form.password.data)
        login_user(user)
        flash("Logged in successfully.", "success")
        return redirect("/home")
    return render_template("login.html", form=form)


@auth.route('/out')
def out():
    """ Logouting user and go to login.html """

    logout_user()
    return redirect("/login")

@auth.route('/registration', methods=['POST', 'GET'])
def registration():
    """ Return registration.html if you don't authorized """
    form = RegistrationForm()
    if form.validate_on_submit():
        return redirect("/login")
    return render_template("registration.html", form=form)

walmart_upc/controllers/main.py
"""
"A universal convention supplies all of maintainability,
clarity, consistency, and a foundation for good programming habits too.
What it doesn't do is insist that you follow it against your will. That's Python!"
—Tim Peters on comp.lang.python, 2001-06-16
"""
import json
import datetime
from bson import ObjectId
from flask import Blueprint, render_template, request,\
 flash, redirect, make_response
from flask_login import  login_required, current_user
import walmart_upc.objects_behevior as model

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
@login_required
def home():
    """ Start page for login user """

    return render_template('home.html', product_header=model.UpcWalmart.get_header_upc())

@main.route('/data-array', methods=['POST'])
@login_required
def data_array():
    """ Data for datateble """

    class JSONEncoder(json.JSONEncoder):
        """ Fix error """

        def default(self, o):
            """



            Args:

              o:



            Returns:



            """

            if isinstance(o, ObjectId):
                return str(o)
            if isinstance(o, (datetime.datetime, datetime.date)):
                return str(o)
            return json.JSONEncoder.default(self, o)

    draw = int(request.form['draw'], base=0) + 1
    user = model.User(current_user)
    data = user.get_upc_limit_sort(int(request.form['start']), int(request.form['length']),\
      request.form['columns[' + request.form['order[0][column]'] + '][data]'],\
      (-1, 1)[request.form['order[0][dir]'] == 'asc'])

    data = json.dumps({"draw": draw,
                       "recordsTotal": user.count_upc(),
                       "recordsFiltered": user.count_upc(),
                       "data":data}, cls=JSONEncoder)
    return data

@main.route('/add-upc', methods=['POST'])
@login_required
def add_upc():
    """ Add walmart object """

    user = model.User(current_user)
    user.set_upc(request.form['upc'])
    if user.set_upc(request.form['upc']) != 1:
        flash("Wrong upc or key!", category='error')
    return redirect("/home")

@main.route('/del-upc', methods=['POST'])
@login_required
def del_upc():
    """ Delete walmart object  """

    user = model.User(current_user)
    user.del_upc(request.form['upc_del'])
    return redirect("/home")

@main.route('/add-file-csv', methods=['POST'])
@login_required
def add_file_csv():
    """ Add upc from csv  """

    user = model.User(current_user)
    err_key = user.set_csv(request.files['fileToUpload'].read())
    if len(err_key) > 0:
        flash("Wrong upc "+str(len(err_key)), category='error')
    return redirect("/home")

@main.route('/add-key', methods=['POST'])
@login_required
def add_key():
    """ Add key walmart """

    user = model.User(current_user)
    key = request.form['key']
    user.set_key(key)
    return redirect("/home")

@main.route('/download-example')
def download_example():
    """ Return csv example """

    csv = """"upc",n"035000521019",n"10001137891","""

    response = make_response(csv)
    response.headers["Content-Disposition"] = "attachment; filename=example.csv"
    return response

@main.route('/download')
@login_required
def download():
    """ Walmart data in csv format  """

    user = model.User(current_user)
    csv = user.get_csv()
    response = make_response(csv)
    response.headers["Content-Disposition"] = "attachment; filename=database.csv"
    return response

@main.route('/Settings', methods=['GET'])
@login_required
def Settings():
    """ Return Settings.html and key user"""

    user = model.User(current_user)
    key = user.key_walmart()
    return render_template('Settings.html', key=key)

walmart_upc/templates/Settings.html
{% extends "adminlte/base_without_nav.html" %}

{% block title %}Log In{% endblock %}
{% block description %}Log into your account!{% endblock %}
{% block bodytag %}hold-transition lockscreen{% endblock %}

{% block body %}

<!-- Automatic element centering -->
<div class="lockscreen-wrapper">
  <div class="lockscreen-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
  </div>
  <!-- User name -->
    <!-- /.lockscreen-image -->

    <!-- lockscreen credentials (contains the form) -->
    <form class="lockscreen-credentials" action="{{ url_for('main.add_key') }}" method="post">
      <div class="input-group">
        <input name="key"  class="form-control" placeholder="{{key}}">

        <div class="input-group-btn">
          <button type="submit" class="btn"><i class="fa fa-arrow-right text-muted"></i></button>
        </div>
      </div>
    </form>
    <!-- /.lockscreen credentials -->

  </div>
  <!-- /.lockscreen-item -->
  <div class="help-block text-center">
    Enter your password to retrieve your session
  </div>
  <div class="text-center">
    <a href="{{ url_for('auth.login') }}">Or sign in as a different user</a>
  </div>
  <div class="lockscreen-footer text-center">
    Copyright &copy; 2014-2015 <b><a href="http://almsaeedstudio.com" class="text-black">Almsaeed Studio</a></b><br>
    All rights reserved
  </div>
</div>
<!-- /.center -->
{% endblock body %}

walmart_upc/templates/home.html
{% extends "adminlte/base.html" %}
{% import "adminlte/layout.html" as layout with context %}
{% import "adminlte/widgets.html" as widgets with context %}

{% block navbar %}
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">
            <!-- Messages: style can be found in dropdown.less-->
   
            <!-- Notifications: style can be found in dropdown.less -->

            <!-- Tasks: style can be found in dropdown.less -->
        
            <!-- User Account: style can be found in dropdown.less -->
            <li class="dropdown user user-menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="glyphicon glyphicon-user"></i>
                <span><i class="caret"></i></span>
              </a>
              <ul class="dropdown-menu">
                <!-- User image -->
                <li class="user-header bg-light-blue">
                  <p>
                  
                    <small>Member since </small>
                  </p>
                </li>
                <!-- Menu Body -->
                <li class="user-body">
                  <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                  </div>
                </li>
                <!-- Menu Footer-->
                <li class="user-footer">
                  <div class="pull-right">
                    <a href="{{ url_for('auth.out') }}" class="btn btn-default btn-flat">Sign out</a>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
{%- endblock navbar %}
{% block sidebar -%}
        <!-- sidebar: style can be found in sidebar.less -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
          <div class="user-panel">
            <div class="pull-left image">
            </div>
            <div class="pull-left info">
              <a href="#">
                <i class="fa fa-circle text-success"></i>
                Online
              </a>
            </div>
          </div>
          <ul class="sidebar-menu">
          <li class="header">HEADER</li>
            <li class="active">
              <a href="{{ url_for('main.home') }}">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
              </a>
            </li>

            <li class="treeview">
              <a href="#">
                <i class="fa fa-folder"></i>
                <span>Options</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li>
                  <a href="{{ url_for('main.Settings') }}">
                    <i class="fa fa-circle-o"></i>
                      Settings
                  </a>

                </li>
              </ul>
            </li>

          </ul>
        <!-- /.sidebar -->
{%- endblock sidebar %}
{% block content_header -%}
          <h1>
            Dashboard
            <small>Preview page</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
          </ol>
{%- endblock content_header %}
{% block content -%}
          <!-- Small boxes (Stat box) -->
          <div class="row">
              <!-- Button trigger modal -->
              <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                  Create
              </button>
              <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#Delete">
                  Delete
              </button>
              <a href="{{ url_for('main.download') }}" >Download csv</a>
              <!-- Modal -->
              <div class="modal fade" id="Delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                      <div class="modal-content">
                          <div class="modal-header">
                              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                              <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                          </div>
                          <div class="modal-body">

                              <form action="{{ url_for('main.del_upc') }}" method="post">
                                  <div class="form-group has-feedback">
                                      <input name="upc_del" placeholder="upc" required="true" class="form-control">
                                      <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                                  </div>
                                  <div class="col-xs-4 col-xs-offset-8">
                                      <button type="submit" class="btn btn-primary btn-block btn-flat">Delete</button>
                                  </div>
                              </form>

                          </div>
                      </div>
                  </div>
              </div>
              <!-- Modal -->
              <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelleFdby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                      <div class="modal-content">
                          <div class="modal-header">
                              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                              <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                          </div>
                          <div class="modal-body">
                              

                              <form action="{{ url_for('main.add_upc') }}" method="post">
                                  <div class="form-group has-feedback">
                                      <input name="upc" placeholder="upc" required="true" class="form-control">
                                      <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                                  </div>
                                      <div class="col-xs-4 col-xs-offset-8">
                                          <button type="submit" class="btn btn-primary btn-block btn-flat">ADD</button>
                                      </div>
                              </form>
                              <form action="{{ url_for('main.add_file_csv') }}" method="post" enctype="multipart/form-data">
                                  Select image to upload:
                                  <div class="form-group has-feedback">
                                      <input type="file" name="fileToUpload" id="fileToUpload">
                                  </div>
                                  <div class="col-xs-4 col-xs-offset-8">
                                      <button type="submit" class="btn btn-primary btn-block btn-flat">ADD</button>
                                  </div>
                            </form>
                        
                          </div>

                          <h3><a href="{{ url_for('main.download_example') }}">download example csv</a></h3>

                      </div>
                  </div>
              </div>
          <!-- Small boxes (Stat box) -->
              <table id="example" class="display">
                  <thead>
                      <tr>
                          {% for key in product_header %}
                          <th>{{key }}</th>
                          {% endfor %}

                      </tr>
                  </thead>
         
              </table>
{%- endblock content %}

walmart_upc/templates/login.html
{% extends "adminlte/base_without_nav.html" %}

{% block title %}Log In{% endblock %}
{% block description %}Log into your account!{% endblock %}
{% block bodytag %}login-page{% endblock %}

{% block body %}

  <div class="login-box">
    <div class="login-logo">
      <strong>Admin</strong>LTE
    </div>
    <div class="login-box-body">
      <p>Log into your account!</p>
      {# Display errors (if there are any). #}
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <ul>
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      {% endwith %}
      {# Render the login form. #}
        <form action="{{ url_for('auth.login') }}" method="post">

            <form role="form" action="{{ url_for('.login') }}" method="post">

                {{ form.hidden_tag() }}



                <div class="form-group">

                    {{ form.username.label }}

                    {% if form.username.errors %}

                        {% for e in form.username.errors %}

                            <p class="help-block">{{ e }}</p>

                        {% endfor %}

                    {% endif %}

                    {{ form.username(class_="form-control") }}

                </div>

                <div class="form-group">

                    {{ form.password.label }}

                    {% if form.password.errors %}

                        {% for e in form.password.errors %}

                            <p class="help-block">{{ e }}</p>

                        {% endfor %}

                    {% endif %}

                    {{ form.password(class_="form-control") }}

                </div>



                <button type="submit" class="btn btn-primary">Submit</button>

            </form>
        </form>

        <form action="{{ url_for('auth.registration') }}" method="get">
            <div class="row">
                <div class="col-xs-4 col-xs-offset-8">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">regisration</button>
                </div>
            </div>
        </form>

    </div>
  </div>

{% endblock %}

walmart_upc/templates/registration.html
{% extends "adminlte/base_without_nav.html" %}

{% block title %}Log In{% endblock %}
{% block description %}Log into your account!{% endblock %}
{% block bodytag %}login-page{% endblock %}

{% block body %}

  <div class="login-box">
    <div class="login-logo">
      <strong>Admin</strong>LTE
    </div>
    <div class="login-box-body">
      <p>Log into your account!</p>
      {# Display errors (if there are any). #}
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <ul>
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      {% endwith %}
      {# Render the login form. #}



        <form action="{{ url_for('auth.registration') }}" method="post">
            <form role="form" action="{{ url_for('.login') }}" method="post">

                {{ form.hidden_tag() }}



                <div class="form-group">

                    {{ form.username.label }}

                    {% if form.username.errors %}

                        {% for e in form.username.errors %}

                            <p class="help-block">{{ e }}</p>

                        {% endfor %}

                    {% endif %}

                    {{ form.username(class_="form-control") }}

                </div>

                <div class="form-group">

                    {{ form.password.label }}

                    {% if form.password.errors %}

                        {% for e in form.password.errors %}

                            <p class="help-block">{{ e }}</p>

                        {% endfor %}

                    {% endif %}

                    {{ form.password(class_="form-control") }}

                </div>

                <div class="form-group">

                    {{ form.password_again.label }}

                    {% if form.password_again.errors %}

                        {% for e in form.password_again.errors %}

                            <p class="help-block">{{ e }}</p>

                        {% endfor %}

                    {% endif %}

                    {{ form.password_again(class_="form-control") }}

                </div>

                <button type="submit" class="btn btn-primary">Submit</button>

            </form>
        </form>


    </div>
  </div>

{% endblock %}