flask_adminlte/__init__.py
#!/usr/bin/env python
# coding=utf8

__version__ = '2.3.3'

import re

from flask import Blueprint, current_app, url_for


class CDN(object):
    """Base class for CDN objects."""
    def get_resource_url(self, filename):
        """Return resource url for filename."""
        raise NotImplementedError


class StaticCDN(object):
    """A CDN that serves content from the local application.

    :param static_endpoint: Endpoint to use.
    :param rev: If ``True``, honor ``ADMINLTE_QUERYSTRING_REVVING``.
    """
    def __init__(self, static_endpoint='static', rev=False):
        self.static_endpoint = static_endpoint
        self.rev = rev

    def get_resource_url(self, filename):
        extra_args = {}

        if self.rev and current_app.config['ADMINLTE_QUERYSTRING_REVVING']:
            extra_args['adminlte'] = __version__

        return url_for(self.static_endpoint, filename=filename, **extra_args)


class WebCDN(object):
    """Serves files from the Web.

    :param baseurl: The baseurl. Filenames are simply appended to this URL.
    """
    def __init__(self, baseurl):
        self.baseurl = baseurl

    def get_resource_url(self, filename):
        return self.baseurl + filename


class ConditionalCDN(object):
    """Serves files from one CDN or another, depending on whether a
    configuration value is set.

    :param confvar: Configuration variable to use.
    :param primary: CDN to use if the configuration variable is ``True``.
    :param fallback: CDN to use otherwise.
    """
    def __init__(self, confvar, primary, fallback):
        self.confvar = confvar
        self.primary = primary
        self.fallback = fallback

    def get_resource_url(self, filename):
        if current_app.config[self.confvar]:
            return self.primary.get_resource_url(filename)
        return self.fallback.get_resource_url(filename)


def adminlte_find_resource(filename, cdn, use_minified=None, local=True):
    """Resource finding function, also available in templates.

    Tries to find a resource, will force SSL depending on
    ``ADMINLTE_CDN_FORCE_SSL`` settings.

    :param filename: File to find a URL for.
    :param cdn: Name of the CDN to use.
    :param use_minified': If set to ``True``/``False``, use/don't use
                          minified. If ``None``, honors
                          ``ADMINLTE_USE_MINIFIED``.
    :param local: If ``True``, uses the ``local``-CDN when
                  ``ADMINLTE_SERVE_LOCAL`` is enabled. If ``False``, uses
                  the ``static``-CDN instead.
    :return: A URL.
    """
    config = current_app.config

    if None == use_minified:
        use_minified = config['ADMINLTE_USE_MINIFIED']

    if use_minified:
        filename = '%s.min.%s' % tuple(filename.rsplit('.', 1))

    cdns = current_app.extensions['adminlte']['cdns']
    resource_url = cdns[cdn].get_resource_url(filename)

    if resource_url.startswith('//') and config['ADMINLTE_CDN_FORCE_SSL']:
        resource_url = 'https:%s' % resource_url

    return resource_url


class AdminLTE(object):
    def __init__(self, app=None):
        if app is not None:
            self.init_app(app)

    def init_app(self, app):
        ADMINLTE_VERSION = re.sub(r'^(\d+\.\d+\.\d+).*', r'\1', __version__)
        JQUERY_VERSION = '2.1.4'
        HTML5SHIV_VERSION = '3.7.0'
        RESPONDJS_VERSION = '1.3.0'

        app.config.setdefault('ADMINLTE_USE_MINIFIED', True)
        app.config.setdefault('ADMINLTE_CDN_FORCE_SSL', False)

        app.config.setdefault('ADMINLTE_QUERYSTRING_REVVING', True)
        app.config.setdefault('ADMINLTE_SERVE_LOCAL', False)

        blueprint = Blueprint(
            'adminlte',
            __name__,
            template_folder='templates',
            static_folder='static',
            static_url_path=app.static_url_path + '/adminlte')

        app.register_blueprint(blueprint)

        app.jinja_env.globals['adminlte_find_resource'] =\
            adminlte_find_resource

        if not hasattr(app, 'extensions'):
            app.extensions = {}

        local = StaticCDN('adminlte.static', rev=True)
        static = StaticCDN()

        def lwrap(cdn, primary=static):
            return ConditionalCDN('ADMINLTE_SERVE_LOCAL', primary, cdn)

        bootstrap = lwrap(
            WebCDN('//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/%s/'
                   % ADMINLTE_VERSION),
            local)

        jquery = lwrap(
            WebCDN('//cdnjs.cloudflare.com/ajax/libs/jquery/%s/'
                   % JQUERY_VERSION),
            local)

        html5shiv = lwrap(
            WebCDN('//cdnjs.cloudflare.com/ajax/libs/html5shiv/%s/'
                   % HTML5SHIV_VERSION))

        respondjs = lwrap(
            WebCDN('//cdnjs.cloudflare.com/ajax/libs/respond.js/%s/'
                   % RESPONDJS_VERSION))

        app.extensions['adminlte'] = {
            'cdns': {
                'local': local,
                'static': static,
                'bootstrap': bootstrap,
                'jquery': jquery,
                'html5shiv': html5shiv,
                'respond.js': respondjs,
            },
        }

walmart_upc/controllers/main.py
"""
"A universal convention supplies all of maintainability,
clarity, consistency, and a foundation for good programming habits too.
What it doesn't do is insist that you follow it against your will. That's Python!"
—Tim Peters on comp.lang.python, 2001-06-16
"""
import json
import datetime
from bson import ObjectId
from flask import Blueprint, render_template, request,\
 flash, redirect, make_response
from flask_login import  login_required, current_user
import walmart_upc.objects_behevior as model

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
@login_required
def home():
    """ Start page for login user """

    return render_template('home.html', product_header=model.UpcWalmart.get_header_upc())

@main.route('/data-array', methods=['POST'])
@login_required
def data_array():
    """ Data for datateble """

    class JSONEncoder(json.JSONEncoder):
        """ Fix error """

        def default(self, o):
            """



            Args:

              o:



            Returns:



            """

            if isinstance(o, ObjectId):
                return str(o)
            if isinstance(o, (datetime.datetime, datetime.date)):
                return str(o)
            return json.JSONEncoder.default(self, o)

    draw = int(request.form['draw'], base=0) + 1
    user = model.User(current_user)
    data = user.get_upc_limit_sort(int(request.form['start']), int(request.form['length']),\
      request.form['columns[' + request.form['order[0][column]'] + '][data]'],\
      (-1, 1)[request.form['order[0][dir]'] == 'asc'])

    data = json.dumps({"draw": draw,
                       "recordsTotal": user.count_upc(),
                       "recordsFiltered": user.count_upc(),
                       "data":data}, cls=JSONEncoder)
    return data

@main.route('/add-upc', methods=['POST'])
@login_required
def add_upc():
    """ Add walmart object """

    user = model.User(current_user)
    user.set_upc(request.form['upc'])
    if user.set_upc(request.form['upc']) != 1:
        flash("Wrong upc or key!", category='error')
    return redirect("/home")

@main.route('/del-upc', methods=['POST'])
@login_required
def del_upc():
    """ Delete walmart object  """

    user = model.User(current_user)
    user.del_upc(request.form['upc_del'])
    return redirect("/home")

@main.route('/add-file-csv', methods=['POST'])
@login_required
def add_file_csv():
    """ Add upc from csv  """

    user = model.User(current_user)
    err_key = user.set_csv(request.files['fileToUpload'].read())
    if len(err_key) > 0:
        flash("Wrong upc "+str(len(err_key)), category='error')
    return redirect("/home")

@main.route('/add-key', methods=['POST'])
@login_required
def add_key():
    """ Add key walmart """

    user = model.User(current_user)
    key = request.form['key']
    user.set_key(key)
    return redirect("/home")

@main.route('/download-example')
def download_example():
    """ Return csv example """

    csv = """"upc",n"035000521019",n"10001137891","""

    response = make_response(csv)
    response.headers["Content-Disposition"] = "attachment; filename=example.csv"
    return response

@main.route('/download')
@login_required
def download():
    """ Walmart data in csv format  """

    user = model.User(current_user)
    csv = user.get_csv()
    response = make_response(csv)
    response.headers["Content-Disposition"] = "attachment; filename=database.csv"
    return response

@main.route('/Settings', methods=['GET'])
@login_required
def Settings():
    """ Return Settings.html and key user"""

    user = model.User(current_user)
    key = user.key_walmart()
    return render_template('Settings.html', key=key)

flask_adminlte/templates/adminlte/base.html
<!DOCTYPE html>
<html>
  <head>
    {%- block head %}
    <title>{% block title %}{% endblock title %}</title>
    {%- block metas %}
    <meta charset="UTF-8">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    {%- endblock metas %}
    {%- block styles %}
    <!-- bootstrap 3.0.2 -->
    <link href="{{ adminlte_find_resource('css/bootstrap.css', cdn='local') }}" rel="stylesheet" type="text/css" />
    <!-- Toastr Notifications -->
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
    <!-- font Awesome -->
    <link href="{{ adminlte_find_resource('css/font-awesome.css', cdn='local') }}" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="{{ adminlte_find_resource('css/ionicons.css', cdn='local') }}" rel="stylesheet" type="text/css" />
    <!-- jvectormap -->
    <link href="{{ adminlte_find_resource('plugins/jvectormap/jquery-jvectormap-1.2.2.css', cdn='local', use_minified=False) }}" rel="stylesheet" type="text/css">
    <!-- Theme style -->
    <link href="{{ adminlte_find_resource('css/AdminLTE.css', cdn='local', use_minified=False) }}" rel="stylesheet" type="text/css" />
    <!-- Skin  -->
    <link href="{{ adminlte_find_resource('css/skins/skin-blue.min.css', cdn='local', use_minified=False) }}" rel="stylesheet" type="text/css" />
    <!-- Pace -->
    <link href="{{ adminlte_find_resource('plugins/pace/pace.css', cdn='local') }}" rel="stylesheet" type="text/css">
      <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.css">

    {%- endblock styles %}
    {%- endblock head %}
  </head>

    <body class="{% block skin %}skin-blue{% endblock %} sidebar-mini">

  <noscript>
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="row">
        <div class="container">
            <div class="col-1-1">
            {% for category, message in messages %}
              <div class="alert-box {{ category }} banner">
               {{ message|safe }}
              </div>
            {% endfor %}
           </div>
        </div>
      </div>
      {% endif %}
    {% endwith %}
  </noscript>


        {% block page_body %}
            <div class="wrapper">
                <header class="main-header">
                    {% block brand %}
                      <a href="#" class="logo">
                          <span class="logo-mini"><strong>LTE</strong></span>
                          <span class="logo-lg">Admin<strong>LTE</strong></span>
                      </a>
                    {% endblock %}

                    <!-- Header Navbar: style can be found in header.less -->
                    <nav class="navbar navbar-static-top" role="navigation">
                      {% block navbar %}
                      {%- endblock navbar %}
                    </nav>

                </header>

                <aside class="main-sidebar">
                    <section class="sidebar">
                      {% block sidebar -%}
                      {%- endblock sidebar %}
                    </section>
                </aside>

                <div class="content-wrapper">

                  <!-- Content Header (Page header) -->
                  <section class="content-header">
                  {% block content_header -%}
                  {%- endblock content_header %}
                  </section>

                  <!-- Main content -->
                  <section class="content">
                  {% block content -%}
                  {%- endblock content %}
                  </section><!-- /.content -->
                </div>
                <footer class="main-footer">
                    <div class="pull-right hidden-xs">
                        {% block version %}
                        <b>Version</b> 2.0.1
                        {% endblock %}
                    </div>
                    {% block copyright %}<strong>Copyright © 2016</strong> All rights reserved.{% endblock %}
                </footer>
            </div>
        {% endblock %}

        {% block tail %}{% endblock %}

    {% block scripts %}
      <!-- jQuery -->
         

      <script src="{{ adminlte_find_resource('jquery.js', cdn='jquery') }}"></script>
      <!-- jQuery UI 1.11.4 -->
      <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
      <!-- Bootstrap -->
      <script src="{{ adminlte_find_resource('js/bootstrap.js', cdn='local') }}"></script>
      <!-- Toastr Notifications -->
      <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
      <!-- PACE -->
      <script src="{{ adminlte_find_resource('js/plugins/pace/pace.js', cdn='local', use_minified=False) }}"></script>
      <!-- Slimscroll -->
      <script src="{{ adminlte_find_resource('js/plugins/slimScroll/jquery.slimscroll.js', cdn='local')}}"></script>
      <!-- Fastclick -->
      <script src="{{ adminlte_find_resource('js/plugins/fastclick/fastclick.js', cdn='local')}}"></script>
      <!-- AdminLTE App -->
      <script src="{{ adminlte_find_resource('js/AdminLTE/app.js', cdn='local', use_minified=False) }}"></script>
      <!-- Sparkline -->
      <script src="{{ adminlte_find_resource('js/plugins/sparkline/jquery.sparkline.js', cdn='local') }}"></script>
      <!-- jvectormap -->
      <script src="{{ adminlte_find_resource('js/plugins/jvectormap/jquery-jvectormap-1.2.2.js', cdn='local') }}"></script>
      <script src="{{ adminlte_find_resource('js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js', cdn='local', use_minified=False) }}"></script>
      <!-- ChartJS 1.0.1 -->
      <script src="{{ adminlte_find_resource('js/plugins/chartjs/Chart.js', cdn='local') }}"></script>
      <script>
        /* turning flask flash messages into js popup notifications */
        window.popupMessages = {{ get_flashed_messages(with_categories=True) | tojson | safe }};
      </script>

      

        <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>
      <!-- Local application JS -->
        <script src="{{ adminlte_find_resource('js/angular.js', cdn='local') }}"></script>

      <script src="{{ adminlte_find_resource('js/app.js', cdn='local', use_minified=False) }}"></script>

        <script>
            $(document).ready(function() {
            $('#example').DataTable({
                processing: true,
                serverSide: true,
                ajax:{
                    url: "{{ url_for('main.data_array') }}",
                    "type": "POST"
                } ,
                columns: [
                      {data: 'upc'},
                      {data: 'salePrice'},
                      {data: 'name'},
                      {data: 'brandName'},
                      {data: 'modelNumber'},
                      {data: 'largeImage'},
                      {data: 'stock'},
                      {data: 'freeShippingOver50Dollars'},
                      {data: 'date_modified'}
                ],
            });
            })
        </script>

    {%- endblock scripts %}

    </body>
</html>

flask_adminlte/templates/adminlte/base_without_nav.html
<!DOCTYPE html>
<html>
  <head>
    {%- block head %}
    <title>{% block title %}{% endblock title %}</title>
    {%- block metas %}
    <meta charset="UTF-8">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    {%- endblock metas %}
    {%- block styles %}
    <!-- bootstrap 3.0.2 -->
    <link href="{{ adminlte_find_resource('css/bootstrap.css', cdn='local') }}" rel="stylesheet" type="text/css" />
    <!-- font Awesome -->
    <link href="{{ adminlte_find_resource('css/font-awesome.css', cdn='local') }}" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="{{ adminlte_find_resource('css/ionicons.css', cdn='local') }}" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{{ adminlte_find_resource('css/AdminLTE.css', cdn='local', use_minified=False) }}" rel="stylesheet" type="text/css" />
    <!-- Skin  -->
    <link href="{{ adminlte_find_resource('css/skins/skin-blue.min.css', cdn='local', use_minified=False) }}" rel="stylesheet" type="text/css" />
      


    {%- endblock styles %}
    {%- endblock head %}

  </head>

  <body class="{% block bodytag %}{% endblock %}">
    {% block body %}{% endblock %}

        {% block tail %}{% endblock %}

    {% block scripts %}
    <!-- jQuery 2.0.2 -->
    <script src="{{ adminlte_find_resource('jquery.js', cdn='jquery') }}"></script>
      <script src="{{ adminlte_find_resource('jquery.dataTables.js', cdn='jquery') }}"></script>

    <!-- Bootstrap -->
    <script src="{{ adminlte_find_resource('js/bootstrap.js', cdn='local') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ adminlte_find_resource('js/AdminLTE/app.js', cdn='local', use_minified=False) }}">  
       
      </script>

      {%- endblock scripts %}

    </body>
</html>

flask_adminlte/templates/adminlte/fixes.html
{% macro ie8() %}
<!--[if lt IE 9]>
      <script src="{{ adminlte_find_resource('html5shiv.js', cdn='local', local=False) }}"></script>
      <script src="{{ adminlte_find_resource('respond.js', cdn='local', local=False) }}"></script>
<![endif]-->
{% endmacro %}

flask_adminlte/templates/adminlte/layout.html
{% macro menu_icon(item) -%}
{% set icon_type = item.get_icon_type() %}
{%- if icon_type %}
  {% set icon_value = item.get_icon_value() %}
  {% if icon_type == 'glyph' %}
    <i class="glyphicon {{ icon_value }}"></i>
  {% elif icon_type == 'fa' %}
    <i class="fa {{ icon_value }}"></i>
  {% elif icon_type == 'image' %}
    <img src="{{ url_for('static', filename=icon_value) }}" alt="menu image">
  {% elif icon_type == 'image-url' %}
    <img src="item.icon_value" alt="menu image">
  {% endif %}
{% endif %}
{%- endmacro %}

{% macro category_menu_icon(item) -%}
  {% set icon_value = item.get_class_name() %}
  <i class="{{icon_value}}"></i>
{%- endmacro %}

{% macro menu() %}

  <div class="user-panel">
    <div class="pull-left image">
      <img src="{{ current_user.custom_data['avatar'] }}" alt="User Image" class="img-circle">
    </div>
    <div class="pull-left info">
      <p>{{ current_user.full_name }}</p>
      <a href="#">
        <i class="fa fa-circle text-success"></i>
        Online
      </a>
    </div>
  </div>

  <li class="header">MAIN NAVIGATION</li>

  {%- for item in admin_view.admin.menu() %}
    {%- if item.is_category() -%}
      {% set children = item.get_children() %}
      {%- if children %}
        {% set class_name = item.get_class_name() %}
        {%- if item.is_active(admin_view) %}
        <li class="active treeview">
        {% else -%}
        <li class="treeview">
        {%- endif %}
          <a href="#">{{ category_menu_icon(item) }}<span>{{ item.name }}</span><i class="fa fa-angle-left pull-right"></i></a>
          <ul class="treeview-menu">
          {%- for child in children -%}
            {% set class_name = child.get_class_name() %}
            {%- if child.is_active(admin_view) %}
            <li class="active{% if class_name %} {{class_name}}{% endif %}">
            {% else %}
            <li{% if class_name %} class="{{class_name}}"{% endif %}>
            {%- endif %}
              <a href="{{ child.get_url() }}">{{ menu_icon(child) }}<span>{{ child.name }}</span></a>
            </li>
          {%- endfor %}
          </ul>
        </li>
      {% endif %}
    {%- else %}
      {%- if item.is_accessible() and item.is_visible() -%}
        {% set class_name = item.get_class_name() %}
        {%- if item.is_active(admin_view) %}
        <li class="active{% if class_name %} {{class_name}}{% endif %}">
        {%- else %}
        <li{% if class_name %} class="{{class_name}}"{% endif %}>
        {%- endif %}
          <a href="{{ item.get_url() }}">{{ menu_icon(item) }}<span>{{ item.name }}</span></a>
        </li>
      {%- endif -%}
    {% endif -%}
  {% endfor %}
{% endmacro %}

{% macro menu_links() %}
  {% for item in admin_view.admin.menu_links() %}
    {% if item.is_accessible() and item.is_visible() %}
      <li>
        <a href="{{ item.get_url() }}">{{ menu_icon(item) }}<span>{{ item.name }}</span></a>
      </li>
    {% endif %}
  {% endfor %}
{% endmacro %}

{% macro messages() %}
  {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
      {% for category, m in messages %}
        {% if category %}
        {% set mapping = {'message': 'info', 'error': 'danger'} %}
        <div class="alert alert-{{ mapping.get(category, 'warning') }} alert-dismissable">
        {% else %}
        <div class="alert alert-dismissable">
        {% endif %}
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          {{ m }}
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
{% endmacro %}

flask_adminlte/templates/adminlte/widgets.html
{% macro small_box(bgcolor="bg-yellow", header="44", percentage=False, body="User Registrations", iconclass="ion ion-person-add", footerlink="#") %}

    <div class="col-lg-3 col-xs-6">
      <!-- small box -->
      <div class="small-box {{bgcolor}}">
        <div class="inner">
          <h3>
            {{header}}{% if percentage %}<sup style="font-size: 20px">%</sup>{% endif %}
          </h3>

          <p>{{body}}</p>
        </div>
        <div class="icon">
          <i class="{{iconclass}}"></i>
        </div>
        <a href="{{footerlink}}" class="small-box-footer">
          More info <i class="fa fa-arrow-circle-right"></i>
        </a>
      </div>
    </div>

{% endmacro %}